image: patgrosse/riotsensors-build
stages:
  - prepare
  - build
  - test
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'eval $(ssh-agent -s)'
  - 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
  - 'mkdir -p ~/.ssh'
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - 'git config --global user.email "riotsensors-build@ci.gitlab.com"'
  - 'git config --global user.name "riotsensors-build"'
getlibs:
  variables:
    GIT_STRATEGY: clone
  stage: prepare
  script:
    - "./prebuild.sh"
  artifacts:
    paths:
    - lib/
build-msba2:
  stage: build
  dependencies:
    - getlibs
  script:
    - "GITLAB_USE_SSH=1 make"
build-native:
  stage: build
  dependencies:
    - getlibs
  script:
    - "GITLAB_USE_SSH=1 make"
  artifacts:
    paths:
    - bin/native/rs-example.elf
    - bin/riotsensors
integrationTest:
  stage: test
  dependencies:
  - getlibs
  - build-native
  script:
    - "git clone git@gitlab.com:patgrosse/riotsensors-example.git"
    - "cd riotsensors-example"
    - "ln -s `pwd`/../lib/RIOT lib/RIOT"
    - "ln -s `pwd`/.. lib/riotsensors"
    - "ln -s `pwd`/../lib/libspt lib/libspt"
    - "GITLAB_USE_SSH=1 BOARD=native make all flash"
    - "tests/test_list.sh"
